local_repository(
    name = "rules_xcodeproj",
    path = "../..",
)

load(
    "@rules_xcodeproj//xcodeproj:repositories.bzl",
    "xcodeproj_rules_dependencies",
)

xcodeproj_rules_dependencies()

load(
    "@build_bazel_rules_apple//apple:repositories.bzl",
    "apple_rules_dependencies",
)

apple_rules_dependencies()

load(
    "@build_bazel_rules_swift//swift:repositories.bzl",
    "swift_rules_dependencies",
)

swift_rules_dependencies()

load(
    "@build_bazel_rules_swift//swift:extras.bzl",
    "swift_rules_extra_dependencies",
)

swift_rules_extra_dependencies()

load(
    "@build_bazel_apple_support//lib:repositories.bzl",
    "apple_support_dependencies",
)

apple_support_dependencies()

# rules_apple_linker used for testing using a different linker

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_apple_linker",
    sha256 = "89a537497197bd3ac1fcdd19c5edbdf296de5fec69b483be56a58c37688322a8",
    strip_prefix = "rules_apple_linker-0.1.6",
    url = "https://github.com/keith/rules_apple_linker/archive/refs/tags/0.1.6.tar.gz",
)

load("@rules_apple_linker//:deps.bzl", "rules_apple_linker_deps")

rules_apple_linker_deps()

# Used for testing shared cache between Intel and Apple silicon

register_execution_platforms("@build_bazel_apple_support//platforms:macos_x86_64")

# External repos for examples

local_repository(
    name = "examples_ios_app_external",
    path = "iOSApp/external",
)

new_local_repository(
    name = "examples_command_line_external",
    build_file = "CommandLine/external/BUILD.tpl",
    path = "CommandLine/external",
)

load(
    "@build_bazel_rules_apple//apple:apple.bzl",
    "provisioning_profile_repository",
)

provisioning_profile_repository(
    name = "local_provisioning_profiles",
)

load(":repositories.bzl", "non_bzlmod_dependencies")

non_bzlmod_dependencies()
