import XcodeProj

extension Generator {
    /// Creates an `XCUserData`.
    static func createXCUserData(
        userName: String,
        customSchemes: [XCScheme],
        autogeneratedSchemes: [AutogeneratedScheme]
    ) -> XCUserData {
        let sortedAutogeneratedSchemes = autogeneratedSchemes
            .sorted { lhs, rhs in
                // xor, prioritize isTopLevel comparison then alphabetical if
                // both scheme are top level or not top level
                guard lhs.isTopLevel == rhs.isTopLevel else {
                    return lhs.isTopLevel
                }
                
                guard lhs.isApplication == rhs.isApplication else {
                    return lhs.isApplication
                }
                
                return lhs.scheme.name < rhs.scheme.name
            }
            .map(\.scheme)

        let schemeUserStates = (customSchemes + sortedAutogeneratedSchemes)
            .enumerated()
            .map { index, scheme in
                return XCSchemeManagement.UserStateScheme(
                    name: "\(scheme.name).xcscheme",
                    shared: true,
                    orderHint: index,
                    isShown: true
                )
            }
        
        return XCUserData(
            userName: userName,
            schemes: [],
            schemeManagement: XCSchemeManagement(
                schemeUserState: schemeUserStates
            )
        )
    }
}
