import CustomDump
import PBXProj
import XCScheme
import XCTest

@testable import xcschemes

final class CreateSchemeTests: XCTestCase {
    func test_buildAction_includesAutogeneratedBuildActions() throws {
        // Arrange

        let target = Target.mock(
            key: "App",
            productType: .application,
            buildableReference: buildableReference(
                name: "App",
                referencedContainer: "container:/tmp/App.xcodeproj"
            )
        )
        let expectedBuildAction = CreateBuildAction.defaultCallable(
            entries: [
                .init(
                    buildableReference: target.buildableReference,
                    buildFor: [.running, .profiling, .analyzing]
                ),
            ],
            postActions: [
                .init(
                    title: #"Build End (DevX & "Logs")"#,
                    escapedScriptText: "echo \"<end & done>\"\n".schemeXmlEscaped,
                    expandVariablesBasedOn: target.buildableReference
                ),
            ],
            preActions: [
                .init(
                    title: #"Build Start (DevX & "Logs")"#,
                    escapedScriptText: "echo \"<start & go>\"\n".schemeXmlEscaped,
                    expandVariablesBasedOn: target.buildableReference
                ),
                .init(
                    title: "Initialize Bazel Build Output Groups File",
                    escapedScriptText: #"""
mkdir -p "${BUILD_MARKER_FILE%/*}"
touch "$BUILD_MARKER_FILE"

"""#.schemeXmlEscaped,
                    expandVariablesBasedOn: target.buildableReference
                ),
                .init(
                    title: "Prepare BazelDependencies",
                    escapedScriptText: #"""
mkdir -p "$PROJECT_DIR"

if [[ "${ENABLE_ADDRESS_SANITIZER:-}" == "YES" || \
      "${ENABLE_THREAD_SANITIZER:-}" == "YES" || \
      "${ENABLE_UNDEFINED_BEHAVIOR_SANITIZER:-}" == "YES" ]]
then
    # TODO: Support custom toolchains once clang.sh supports them
    cd "$INTERNAL_DIR" || exit 1
    ln -shfF "$DEVELOPER_DIR/Toolchains/XcodeDefault.xctoolchain/usr/lib" lib
fi

"""#.schemeXmlEscaped,
                    expandVariablesBasedOn: target.buildableReference
                ),
            ],
            runPostActionsOnFailure: true
        )

        // Act

        let scheme = try createSchemeWithDefaults(
            schemeInfo: .mock(
                name: "Scheme",
                run: .mock(
                    launchTarget: .target(primary: target, extensionHost: nil),
                    runBuildPostActionsOnFailure: true
                ),
                profile: .mock(
                    launchTarget: .target(primary: target, extensionHost: nil)
                ),
                executionActions: [
                    .init(
                        title: #"Build Start (DevX & "Logs")"#,
                        scriptText: "echo \"<start & go>\"\n",
                        action: .build,
                        isPreAction: true,
                        target: target,
                        order: -200
                    ),
                    .init(
                        title: #"Build End (DevX & "Logs")"#,
                        scriptText: "echo \"<end & done>\"\n",
                        action: .build,
                        isPreAction: false,
                        target: target,
                        order: 100
                    ),
                ]
            )
        )

        let buildAction = try XCTUnwrap(extractBuildAction(from: scheme))

        // Assert

        XCTAssertNoDifference(buildAction, expectedBuildAction)
    }

    func test_testAction_usesFirstTestableForCustomLLDBInitFile() throws {
        // Arrange

        let buildOnlyTarget = Target.mock(
            key: "BuildOnly",
            productType: .staticLibrary,
            buildableReference: buildableReference(
                name: "BuildOnly",
                referencedContainer: "container:/tmp/BuildOnly.xcodeproj"
            )
        )
        let testableTarget = Target.mock(
            key: "Tests",
            productType: .unitTestBundle,
            buildableReference: buildableReference(
                name: "Tests",
                referencedContainer: "container:/tmp/Tests.xcodeproj"
            )
        )
        let expectedTestAction = createExpectedTestAction(
            buildableReference: testableTarget.buildableReference
        )

        // Act

        let scheme = try createSchemeWithDefaults(
            schemeInfo: .mock(
                name: "Scheme",
                test: .mock(
                    buildTargets: [buildOnlyTarget],
                    testTargets: [.init(target: testableTarget, isEnabled: true)]
                )
            )
        )

        let testAction = try XCTUnwrap(extractTestAction(from: scheme))

        // Assert

        XCTAssertNoDifference(testAction, expectedTestAction)
    }

    func test_profileAction_usesProfileTargetForCustomLLDBInitFile() throws {
        // Arrange

        let runTarget = Target.mock(
            key: "Run",
            productType: .application,
            buildableReference: buildableReference(
                name: "Run",
                referencedContainer: "container:/tmp/Run.xcodeproj"
            )
        )
        let profileTarget = Target.mock(
            key: "Profile",
            productType: .application,
            buildableReference: buildableReference(
                name: "Profile",
                referencedContainer: "container:/tmp/Profile.xcodeproj"
            )
        )
        let expectedProfileAction = createExpectedProfileAction(
            buildableReference: profileTarget.buildableReference
        )

        // Act

        let scheme = try createSchemeWithDefaults(
            schemeInfo: .mock(
                name: "Scheme",
                run: .mock(
                    launchTarget: .target(
                        primary: runTarget,
                        extensionHost: nil
                    )
                ),
                profile: .mock(
                    launchTarget: .target(
                        primary: profileTarget,
                        extensionHost: nil
                    )
                )
            )
        )

        let profileAction = try XCTUnwrap(extractProfileAction(from: scheme))

        // Assert

        XCTAssertNoDifference(profileAction, expectedProfileAction)
    }

    func test_launchAction_pathRunnableDoesNotUseBuildEntryLLDBInitFile() throws {
        // Arrange

        let buildOnlyTarget = Target.mock(
            key: "BuildOnly",
            productType: .application,
            buildableReference: buildableReference(
                name: "BuildOnly",
                referencedContainer: "container:/tmp/BuildOnly.xcodeproj"
            )
        )
        let expectedLaunchAction = CreateLaunchAction.defaultCallable(
            buildConfiguration: "Debug",
            commandLineArguments: [],
            customLLDBInitFile: nil,
            customWorkingDirectory: nil,
            enableAddressSanitizer: false,
            enableThreadSanitizer: false,
            enableUBSanitizer: false,
            enableMainThreadChecker: false,
            enableThreadPerformanceChecker: false,
            environmentVariables: [],
            postActions: [],
            preActions: [],
            runnable: .path(path: "/tmp/tool"),
            storeKitConfiguration: nil
        )

        // Act

        let scheme = try createSchemeWithDefaults(
            schemeInfo: .mock(
                name: "Scheme",
                run: .mock(
                    buildTargets: [buildOnlyTarget],
                    launchTarget: .path("/tmp/tool")
                )
            )
        )

        let launchAction = try XCTUnwrap(extractLaunchAction(from: scheme))

        // Assert

        XCTAssertNoDifference(launchAction, expectedLaunchAction)
    }

    func test_runTestAndProfileActions_includeAutogeneratedActions() throws {
        // Arrange

        let target = Target.mock(
            key: "App",
            productType: .application,
            buildableReference: buildableReference(
                name: "App",
                referencedContainer: "container:/tmp/App.xcodeproj"
            )
        )
        let runPreAction = ExecutionAction(
            title: #"Run Start (DevX & "Logs")"#,
            escapedScriptText: "echo \"<run start & go>\"\n".schemeXmlEscaped,
            expandVariablesBasedOn: target.buildableReference
        )
        let runPostAction = ExecutionAction(
            title: #"Run End (DevX & "Logs")"#,
            escapedScriptText: "echo \"<run end & done>\"\n".schemeXmlEscaped,
            expandVariablesBasedOn: target.buildableReference
        )
        let testPreAction = ExecutionAction(
            title: #"Test Start (DevX & "Logs")"#,
            escapedScriptText: "echo \"<test start & go>\"\n".schemeXmlEscaped,
            expandVariablesBasedOn: target.buildableReference
        )
        let testPostAction = ExecutionAction(
            title: #"Test End (DevX & "Logs")"#,
            escapedScriptText: "echo \"<test end & done>\"\n".schemeXmlEscaped,
            expandVariablesBasedOn: target.buildableReference
        )
        let profilePreAction = ExecutionAction(
            title: #"Profile Start (DevX & "Logs")"#,
            escapedScriptText: "echo \"<profile start & go>\"\n".schemeXmlEscaped,
            expandVariablesBasedOn: target.buildableReference
        )
        let profilePostAction = ExecutionAction(
            title: #"Profile End (DevX & "Logs")"#,
            escapedScriptText: "echo \"<profile end & done>\"\n".schemeXmlEscaped,
            expandVariablesBasedOn: target.buildableReference
        )
        let expectedLaunchAction = CreateLaunchAction.defaultCallable(
            buildConfiguration: "Debug",
            commandLineArguments: [],
            customLLDBInitFile: "/tmp/App.xcodeproj/rules_xcodeproj/bazel.lldbinit",
            customWorkingDirectory: nil,
            enableAddressSanitizer: false,
            enableThreadSanitizer: false,
            enableUBSanitizer: false,
            enableMainThreadChecker: false,
            enableThreadPerformanceChecker: false,
            environmentVariables: [],
            postActions: [runPostAction],
            preActions: [
                runPreAction,
                updateLldbInitAndCopyDSYMsAction(
                    buildableReference: target.buildableReference
                ),
            ],
            runnable: .plain(buildableReference: target.buildableReference),
            storeKitConfiguration: nil
        )
        let expectedTestAction = CreateTestAction.defaultCallable(
            appLanguage: nil,
            appRegion: nil,
            codeCoverage: false,
            buildConfiguration: "Debug",
            commandLineArguments: [],
            customLLDBInitFile: nil,
            enableAddressSanitizer: false,
            enableThreadSanitizer: false,
            enableUBSanitizer: false,
            enableMainThreadChecker: false,
            enableThreadPerformanceChecker: false,
            environmentVariables: [],
            expandVariablesBasedOn: nil,
            postActions: [testPostAction],
            preActions: [testPreAction],
            testables: [],
            useLaunchSchemeArgsEnv: true
        )
        let expectedProfileAction = CreateProfileAction.defaultCallable(
            buildConfiguration: "Debug",
            commandLineArguments: [],
            customLLDBInitFile: "/tmp/App.xcodeproj/rules_xcodeproj/bazel.lldbinit",
            customWorkingDirectory: nil,
            environmentVariables: [],
            postActions: [profilePostAction],
            preActions: [
                profilePreAction,
                updateLldbInitAndCopyDSYMsAction(
                    buildableReference: target.buildableReference
                ),
            ],
            useLaunchSchemeArgsEnv: true,
            runnable: .plain(buildableReference: target.buildableReference)
        )

        // Act

        let scheme = try createSchemeWithDefaults(
            schemeInfo: .mock(
                name: "Scheme",
                test: .mock(),
                run: .mock(
                    launchTarget: .target(primary: target, extensionHost: nil),
                    runBuildPostActionsOnFailure: true
                ),
                profile: .mock(
                    launchTarget: .target(primary: target, extensionHost: nil)
                ),
                executionActions: [
                    .init(
                        title: #"Run Start (DevX & "Logs")"#,
                        scriptText: "echo \"<run start & go>\"\n",
                        action: .run,
                        isPreAction: true,
                        target: target,
                        order: -10
                    ),
                    .init(
                        title: #"Run End (DevX & "Logs")"#,
                        scriptText: "echo \"<run end & done>\"\n",
                        action: .run,
                        isPreAction: false,
                        target: target,
                        order: 10
                    ),
                    .init(
                        title: #"Test Start (DevX & "Logs")"#,
                        scriptText: "echo \"<test start & go>\"\n",
                        action: .test,
                        isPreAction: true,
                        target: target,
                        order: -20
                    ),
                    .init(
                        title: #"Test End (DevX & "Logs")"#,
                        scriptText: "echo \"<test end & done>\"\n",
                        action: .test,
                        isPreAction: false,
                        target: target,
                        order: 20
                    ),
                    .init(
                        title: #"Profile Start (DevX & "Logs")"#,
                        scriptText: "echo \"<profile start & go>\"\n",
                        action: .profile,
                        isPreAction: true,
                        target: target,
                        order: -30
                    ),
                    .init(
                        title: #"Profile End (DevX & "Logs")"#,
                        scriptText: "echo \"<profile end & done>\"\n",
                        action: .profile,
                        isPreAction: false,
                        target: target,
                        order: 30
                    ),
                ]
            )
        )

        let launchAction = try XCTUnwrap(extractLaunchAction(from: scheme))
        let testAction = try XCTUnwrap(extractTestAction(from: scheme))
        let profileAction = try XCTUnwrap(extractProfileAction(from: scheme))

        // Assert

        XCTAssertNoDifference(launchAction, expectedLaunchAction)
        XCTAssertNoDifference(testAction, expectedTestAction)
        XCTAssertNoDifference(profileAction, expectedProfileAction)
    }
}

private func createSchemeWithDefaults(
    schemeInfo: SchemeInfo
) throws -> String {
    try Generator.CreateScheme.defaultCallable(
        defaultXcodeConfiguration: "Debug",
        extensionPointIdentifiers: [:],
        schemeInfo: schemeInfo,
        createAnalyzeAction: CreateAnalyzeAction(),
        createArchiveAction: CreateArchiveAction(),
        createBuildAction: CreateBuildAction(),
        createLaunchAction: CreateLaunchAction(),
        createProfileAction: CreateProfileAction(),
        createSchemeXML: XCScheme.CreateScheme(),
        createTestAction: CreateTestAction()
    ).scheme
}

private func extractTestAction(from scheme: String) -> String? {
    extractElement(named: "TestAction", from: scheme)
}

private func extractBuildAction(from scheme: String) -> String? {
    extractElement(named: "BuildAction", from: scheme)
}

private func extractProfileAction(from scheme: String) -> String? {
    extractElement(named: "ProfileAction", from: scheme)
}

private func extractLaunchAction(from scheme: String) -> String? {
    extractElement(named: "LaunchAction", from: scheme)
}

private func extractElement(named name: String, from scheme: String) -> String? {
    guard
        let start = scheme.range(of: "   <\(name)"),
        let end = scheme.range(of: "</\(name)>")
    else {
        return nil
    }

    return String(scheme[start.lowerBound ..< end.upperBound])
}

private func buildableReference(
    name: String,
    referencedContainer: String
) -> BuildableReference {
    return .init(
        blueprintIdentifier: "\(name)_blueprintIdentifier",
        buildableName: "\(name)_buildableName",
        blueprintName: name,
        referencedContainer: referencedContainer
    )
}

private func createExpectedProfileAction(
    buildableReference: BuildableReference
) -> String {
    return CreateProfileAction.defaultCallable(
        buildConfiguration: "Debug",
        commandLineArguments: [],
        customLLDBInitFile: "/tmp/Profile.xcodeproj/rules_xcodeproj/bazel.lldbinit",
        customWorkingDirectory: nil,
        environmentVariables: [],
        postActions: [],
        preActions: [updateLldbInitAndCopyDSYMsAction(
            buildableReference: buildableReference
        )],
        useLaunchSchemeArgsEnv: true,
        runnable: .plain(buildableReference: buildableReference)
    )
}

private func createExpectedTestAction(
    buildableReference: BuildableReference
) -> String {
    return CreateTestAction.defaultCallable(
        appLanguage: nil,
        appRegion: nil,
        codeCoverage: false,
        buildConfiguration: "Debug",
        commandLineArguments: [],
        customLLDBInitFile: "/tmp/Tests.xcodeproj/rules_xcodeproj/bazel.lldbinit",
        enableAddressSanitizer: false,
        enableThreadSanitizer: false,
        enableUBSanitizer: false,
        enableMainThreadChecker: false,
        enableThreadPerformanceChecker: false,
        environmentVariables: [],
        expandVariablesBasedOn: buildableReference,
        postActions: [],
        preActions: [updateLldbInitAndCopyDSYMsAction(
            buildableReference: buildableReference
        )],
        testables: [
            .init(
                buildableReference: buildableReference,
                isSkipped: false
            ),
        ],
        useLaunchSchemeArgsEnv: false
    )
}

private func updateLldbInitAndCopyDSYMsAction(
    buildableReference: BuildableReference
) -> ExecutionAction {
    return .init(
        title: "Update .lldbinit and copy dSYMs",
        escapedScriptText: #"""
"$BAZEL_INTEGRATION_DIR/create_lldbinit.sh"
"$BAZEL_INTEGRATION_DIR/copy_dsyms.sh"

"""#.schemeXmlEscaped,
        expandVariablesBasedOn: buildableReference
    )
}
