disabled_rules:
  - todo

excluded:
  # Exclude test files
  - "**/test/**/*.swift"
  - "**/*Tests/*.swift"

trailing_comma:
  # Multi-line collection literals should have trailing commas.
  mandatory_comma: true
