disabled_rules:
  - function_body_length
  - function_parameter_count
  - identifier_name
  - large_tuple
  - opening_brace
  - todo

excluded:
  # Exclude test files
  - "**/test"
  - "**/*Tests"
  # Exclude external files
  - "**/bazel-output-base"

trailing_comma:
  # Multi-line collection literals should have trailing commas.
  mandatory_comma: true
