"""Specifies the supported Bazel versions."""

CURRENT_BAZEL_VERSION = "5.0.0"

OTHER_BAZEL_VERSIONS = [
    "6.0.0-pre.20220223.1",
]

SUPPORTED_BAZEL_VERSIONS = [
    CURRENT_BAZEL_VERSION,
] + OTHER_BAZEL_VERSIONS
