#!/usr/bin/env bash

# This file exists to help IDE helpers (e.g., vim+ALE) to execute swiftlint
# using this project's configuration.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null && pwd)"

swiftlint lint --config "${script_dir}/.swiftlint.yml" "$@"
