############
## Project
############
name: ExampleProject

############
## Options
############
## In this part we will override some project properties

options:
  # Select the minimum xcodegen version that could generate this project
  minimumXcodeGenVersion: 2.10

  # Create empty directories in the final project too
  generateEmptyDirectories: true

  # Select deployment target. In this particular case will be use iOS, but
  # we include the example to define it to watchOS, tvOS or macOS
  deploymentTarget:
    iOS: "17.4"
    # watchOS: "6.0"
    # tvOS: "15.0"
    # macOS: "11.0"

#############
## Settings
#############

settings:
  # Following properties will be override properties that you could find
  # into Build settings directory. We will rewrite some for all default variants
  # created by default for xcodegen, Debug and Release.
  IPHONEOS_DEPLOYMENT_TARGET: "17.4"
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

############
## Targets
############

# Finally we will create our targets. Rememeber we have three of them:
# - A core package (that will depends on Alamofire)
# - A test target for this core package
# - An app target

targets:

  # Name for our app target
  ExampleProject:
    # choose application as a type. There a so many types to select here (framework, extensions ...)
    type: application
    # choose destination platform
    platform: iOS
    deploymentTarget: 17.4
    sources:
      # Where app files will be found. Remember you could use patterns and exclusions too!
      - path: app/sources
        group: app
    settings:
      # Select the bundle identifier
      PRODUCT_BUNDLE_IDENTIFIER: "com.example.core"
      CC:
         - "$(PROJECT_DIR)/Stubs/clang_shim.sh"
      CXX:
          - "$(PROJECT_DIR)/Stubs/clang_shim.sh"
      LD:
          - "$(PROJECT_DIR)/Stubs/ld"
      SWIFT_EXEC:
          - "$(PROJECT_DIR)/Stubs/swiftc"
        
      # Select where Info.plist will be found
      INFOPLIST_FILE: app/Info.plist
      MARKETING_VERSION: 1.0.0
    entitlements:
      path: app/Debug.entitlements
      properties:
        com.apple.security.application-groups: group.com.example.core
    info:
      path: app/Info.plist
      properties:
        CFBundleDisplayName: "MyApp"
