cc_binary(
    name = "tool",
    srcs = ["main.c"],
    visibility = ["//visibility:public"],
    deps = [
        "//cc/lib:cc_lib",
        "//cc/lib2:cc_lib2",
        "//cc/lib3:cc_lib3",
        "@examples_cc_external//:lib",
    ],
)
