"""Targets meant to match scheme auto-generation exclude patterns"""

load(
    "@build_bazel_rules_swift//swift:swift.bzl",
    "swift_library",
)

swift_library(
    name = "UndesiredScheme_Swift",
    srcs = ["UndesiredScheme.swift"],
    visibility = ["//iOSApp/Source:__pkg__"],
)

swift_library(
    name = "UnwantedScheme_Swift",
    srcs = ["UnwantedScheme.swift"],
    visibility = ["//iOSApp/Source:__pkg__"],
)
