load(
    ":get_file_from_objc_provider_tests.bzl",
    "get_file_from_objc_provider_test_suite",
)
load(":get_file_tests.bzl", "get_file_test_suite")

get_file_from_objc_provider_test_suite(name = "get_file_from_objc_provider")

get_file_test_suite(name = "get_file")
