load("//xcodeproj:xcodeproj.bzl", "xcodeproj")
load(":xcodeproj_targets.bzl", "XCODEPROJ_TARGETS")

xcodeproj(
    name = "xcodeproj",
    project_name = "TvOS App",
    tags = ["manual"],
    targets = XCODEPROJ_TARGETS,
)
