load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "XCTestFix",
    testonly = True,
    srcs = glob(["**/*.swift"]),
    module_name = "XCTestFix",
    tags = ["manual"],
    visibility = ["//visibility:public"],
)
