load("//examples/integration/CommandLine:xcodeproj_targets.bzl", "XCODEPROJ_TARGETS")
load("//xcodeproj:testing.bzl", "xcodeproj_fixture")

xcodeproj_fixture(
    top_level_targets = XCODEPROJ_TARGETS,
)
