load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "Utils",
    srcs = glob(["**/*.swift"]),
    module_name = "Utils",
    visibility = ["//visibility:public"],
)
