test_suite(
    name = "iOSAppTestSuite",
    tags = ["manual"],
    tests = [
        "//iOSApp/Test/ObjCUnitTests:iOSAppObjCUnitTests",
        "//iOSApp/Test/SwiftUnitTests:iOSAppSwiftUnitTests",
    ],
    visibility = ["@rules_xcodeproj//xcodeproj:generated"],
)
