load("//xcodeproj:xcodeproj.bzl", "xcodeproj")
load(":xcodeproj_targets.bzl", "XCODEPROJ_TARGETS")

xcodeproj(
    name = "xcodeproj",
    project_name = "macOS App",
    tags = ["manual"],
    top_level_targets = XCODEPROJ_TARGETS,
)
