load("//xcodeproj:xcodeproj.bzl", "xcodeproj")
load(":xcodeproj_targets.bzl", "XCODEPROJ_TARGETS")

xcodeproj(
    name = "xcodeproj",
    project_name = "iOS App",
    targets = XCODEPROJ_TARGETS,
    tags = ["manual"],
)
