load("//xcodeproj:xcodeproj.bzl", "xcodeproj")

xcodeproj(
    name = "xcodeproj",
    project_name = "iOS App",
    targets = [
        "//examples/ios_app/Example",
        "//examples/ios_app/ExampleTests",
        "//examples/ios_app/ExampleUITests",
    ],
    tags = ["manual"],
    visibility = ["//visibility:public"],
)
