load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
    name = "com_github_buildbuddy_io_rules_xcodeproj",
    path = "../..",
)

load(
    "@com_github_buildbuddy_io_rules_xcodeproj//xcodeproj:repositories.bzl",
    "xcodeproj_rules_dependencies",
)

xcodeproj_rules_dependencies()

load(
    "@build_bazel_rules_apple//apple:repositories.bzl",
    "apple_rules_dependencies",
)

apple_rules_dependencies()

load(
    "@build_bazel_rules_swift//swift:repositories.bzl",
    "swift_rules_dependencies",
)

swift_rules_dependencies()

load(
    "@build_bazel_rules_swift//swift:extras.bzl",
    "swift_rules_extra_dependencies",
)

swift_rules_extra_dependencies()

load(
    "@build_bazel_apple_support//lib:repositories.bzl",
    "apple_support_dependencies",
)

apple_support_dependencies()

# External repos for examples

local_repository(
    name = "examples_ios_app_external",
    path = "external",
)

SWIFTSNAPSHOTTESTING_VERSION = "88f6e2c0afe04221fcfb1601a2ecaad83115a05f"
http_archive(
    name = "SwiftSnapshotTesting",
    url = "https://github.com/pointfreeco/swift-snapshot-testing/archive/%s.zip" % SWIFTSNAPSHOTTESTING_VERSION,
    sha256 = "ab04012658d2eabe6615a830f3cd54702e2fcec19e0d6a579eabe7103863d8c6",
    build_file_content = """
load(
    "@build_bazel_rules_swift//swift:swift.bzl",
    "swift_library"
)

swift_library(
    name = "SnapshotTesting",
    module_name = "SnapshotTesting",
    test_only = True,
    srcs = glob(["Sources/SnapshotTesting/**/*.swift"], [
        "Sources/SnapshotTesting/Snapshotting/*.swift"
    ], allow_empty = False) + [
        "Sources/SnapshotTesting/Snapshotting/Any.swift",
        "Sources/SnapshotTesting/Snapshotting/Data.swift",
        "Sources/SnapshotTesting/Snapshotting/String.swift",
        "Sources/SnapshotTesting/Snapshotting/Codable.swift",
        "Sources/SnapshotTesting/Snapshotting/URLRequest.swift",
        "Sources/SnapshotTesting/Snapshotting/Description.swift",
        "Sources/SnapshotTesting/Snapshotting/CaseIterable.swift",
    ],
    visibility = ["//visibility:public"]
)
    """,
    strip_prefix = "swift-snapshot-testing-%s" % SWIFTSNAPSHOTTESTING_VERSION
)
