local_repository(
    name = "com_github_buildbuddy_io_rules_xcodeproj",
    path = "../..",
)

load(
    "@com_github_buildbuddy_io_rules_xcodeproj//xcodeproj:repositories.bzl",
    "xcodeproj_rules_dependencies",
)

xcodeproj_rules_dependencies()

load(
    "@build_bazel_rules_apple//apple:repositories.bzl",
    "apple_rules_dependencies",
)

apple_rules_dependencies()

load(
    "@build_bazel_rules_swift//swift:repositories.bzl",
    "swift_rules_dependencies",
)

swift_rules_dependencies()

load(
    "@build_bazel_rules_swift//swift:extras.bzl",
    "swift_rules_extra_dependencies",
)

swift_rules_extra_dependencies()

load(
    "@build_bazel_apple_support//lib:repositories.bzl",
    "apple_support_dependencies",
)

apple_support_dependencies()

# rules_apple_linker used for testing using a different linker

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_apple_linker",
    sha256 = "988979ad64ab210a9e952622398f37cd1f768ff5e51fd526ba1c5ac78a2480aa",
    strip_prefix = "rules_apple_linker-0.1.3",
    url = "https://github.com/keith/rules_apple_linker/archive/refs/tags/0.1.3.tar.gz",
)

load("@rules_apple_linker//:deps.bzl", "rules_apple_linker_deps")

rules_apple_linker_deps()

# External repos for examples

local_repository(
    name = "examples_ios_app_external",
    path = "external",
)

http_archive(
    name = "FXPageControl",
    url = "https://github.com/nicklockwood/FXPageControl/archive/refs/tags/1.5.tar.gz",
    sha256 = "1610603d6ccfbc80b17aa2944c2587f4800c06a4e229303f431091e4e2e7a6d1",
    build_file_content = """
objc_library(
    name = "FXPageControl",
    module_name = "FXPageControl",
    hdrs = ["FXPageControl/FXPageControl.h"],
    srcs = ["FXPageControl/FXPageControl.m"],
    visibility = [
        "//visibility:public",
    ]
)
""",
    strip_prefix = "FXPageControl-1.5",
)
