exports_files(["README.md"])

# Release

filegroup(
    name = "release_files",
    srcs = [
        "//" + package_name() + "/legacy:release_files",
    ],
    tags = ["manual"],
    visibility = ["//:__subpackages__"],
)
