load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# TODO: Undo this `rules_apple` bump once there's a new version of `rules_ios` consuming a newer `rules_apple`
http_archive(
    name = "build_bazel_rules_apple",
    sha256 = "1e152d031de08e98ca6c8078cd36f31bf670c1bea7bc9ab3692a81589e6a8569",
    strip_prefix = "rules_apple-5150ef97f52e4044c0702b16c4b7c0b758204f70",
    url = "https://github.com/bazelbuild/rules_apple/archive/5150ef97f52e4044c0702b16c4b7c0b758204f70.tar.gz",
)

http_archive(
    name = "build_bazel_rules_ios",
    sha256 = "88dc6c5d1aade86bc4e26cbafa62595dffd9f3821f16e8ba8461f372d66a5783",
    url = "https://github.com/bazel-ios/rules_ios/releases/download/2.1.0/rules_ios.2.1.0.tar.gz",
)

load(
    "@build_bazel_rules_ios//rules:repositories.bzl",
    "rules_ios_dependencies",
)

rules_ios_dependencies()

local_repository(
    name = "rules_xcodeproj",
    path = "../..",
)

load(
    "@rules_xcodeproj//xcodeproj:repositories.bzl",
    "xcodeproj_rules_dependencies",
)

xcodeproj_rules_dependencies()

load(
    "@build_bazel_rules_apple//apple:repositories.bzl",
    "apple_rules_dependencies",
)

apple_rules_dependencies()

load(
    "@build_bazel_rules_swift//swift:repositories.bzl",
    "swift_rules_dependencies",
)

swift_rules_dependencies()

load(
    "@build_bazel_rules_swift//swift:extras.bzl",
    "swift_rules_extra_dependencies",
)

swift_rules_extra_dependencies()

load(
    "@build_bazel_apple_support//lib:repositories.bzl",
    "apple_support_dependencies",
)

apple_support_dependencies()

load(
    "@build_bazel_rules_apple//apple:apple.bzl",
    "provisioning_profile_repository",
)

provisioning_profile_repository(
    name = "local_provisioning_profiles",
)
