load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "build_proxy_manifest_tests",
    srcs = ["build_proxy_manifest_tests.py"],
    deps = ["//xcodeproj/internal:build_proxy_manifest_lib"],
)
