py_binary(
    name = "extensionpointidentifiers_parser",
    srcs = ["extensionpointidentifiers_parser.py"],
    python_version = "PY3",
    srcs_version = "PY3",
    # TODO: Restrict visibility
    visibility = ["//visibility:public"],
)
