load(":fixtures.bzl", "update_fixtures")

update_fixtures(
    name = "update",
    tags = ["manual"],
    targets = [
        "//test/fixtures/ios_app:xcodeproj",
        "//test/fixtures/generator:xcodeproj",
    ],
)
