load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "Lib",
    srcs = ["Lib.swift"],
    module_name = "Lib",
    tags = ["manual"],
    visibility = ["//visibility:public"],
)
