load("//examples/tvos_app:xcodeproj_targets.bzl", "XCODEPROJ_TARGETS")
load("//xcodeproj:testing.bzl", "xcodeproj_fixture")

xcodeproj_fixture(
    archived_bundles_allowed = True,
    targets = XCODEPROJ_TARGETS,
)
