cc_binary(
    name = "tool",
    srcs = ["main.c"],
    visibility = ["//visibility:public"],
    deps = [
        "//examples/cc/lib",
        "//examples/cc/lib2",
        "@examples_cc_external//:lib",
    ],
)
