cc_binary(
    name = "tool",
    srcs = ["main.c"],
    visibility = ["//visibility:public"],
    deps = [
        "//lib",
        "//lib2",
        "//lib3",
        "@examples_cc_external//:lib",
    ],
)
