# Files in this package are used to create documentation files. See
# `//docs/BUILD.bazel` for how they are used. Because of this, some `bzl` might
# have empty or odd looking docstrings. This is on purpose to make Stardoc
# render pieces of the documentation the way we want.

exports_files(glob(["*"]))
