name: 'Check commit message style'

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-commit-message-style:
    name: Check commit message style
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: mristin/opinionated-commit-message@v3.0.0
        with:
          allow-one-liners: 'true'
          additional-verbs: 'color,colorize,copy,embed,expose,properly,silence,symlink,split'
          max-subject-line-length: '80'
          skip-body-check: 'true'
