load("//tools/generator:xcodeproj_targets.bzl", "get_xcode_schemes", "get_xcodeproj_targets")
load("//xcodeproj:testing.bzl", "xcodeproj_fixture")

xcodeproj_fixture(
    schemes = get_xcode_schemes(),
    targets = get_xcodeproj_targets(),
)
